#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f *.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace topf1.sv --exe topf1_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vtopf1.mk Vtopf1

# run executable simulation file
echo "\nRunning simulation"
obj_dir/Vtopf1
echo "\nSimulation completed"

